name: Unit Test

on:
  push:
    branches: [ feature/** ]

jobs:
  unittest:
    name: Unit Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x ]

    steps:
      # 현재 레포지토리 코드 업로드
      - name: Checkout my code
        uses: actions/checkout@v3

      # Node.js 설치
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      
      # Yarn 설치
      - name: Generate yarn
        run: npm install -g yarn
      
      # 필요 package install
      - name: Install Dependencies
        run: yarn install

      # 유닛 테스트
      - name: Run Unit Test
        run: yarn test
